package com.xf.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "STATION".
 */
public class Station {

    private String stationName;
    private String stationCode;
    private String fullPY;
    private String shortPY;
    private String section;
    private Boolean isShow;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Station() {
    }

    public Station(String stationName, String stationCode, String fullPY, String shortPY, String section, Boolean isShow) {
        this.stationName = stationName;
        this.stationCode = stationCode;
        this.fullPY = fullPY;
        this.shortPY = shortPY;
        this.section = section;
        this.isShow = isShow;
    }

    public String getStationName() {
        return stationName;
    }

    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    public String getStationCode() {
        return stationCode;
    }

    public void setStationCode(String stationCode) {
        this.stationCode = stationCode;
    }

    public String getFullPY() {
        return fullPY;
    }

    public void setFullPY(String fullPY) {
        this.fullPY = fullPY;
    }

    public String getShortPY() {
        return shortPY;
    }

    public void setShortPY(String shortPY) {
        this.shortPY = shortPY;
    }

    public String getSection() {
        return section;
    }

    public void setSection(String section) {
        this.section = section;
    }

    public Boolean getIsShow() {
        return isShow;
    }

    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
